/**
 * DTO and Command Model Type Definitions for Szybkie Kalorie API
 *
 * This file contains all Data Transfer Object (DTO) types and Command Models
 * used by the REST API. All types are derived from the database schema types
 * defined in src/db/database.types.ts to ensure type safety and consistency.
 *
 * Organization:
 * 1. Common Types (Pagination, Error Handling)
 * 2. Profile DTOs
 * 3. Calorie Goals DTOs
 * 4. AI Generations DTOs
 * 5. Meals DTOs
 * 6. Daily Progress DTOs
 */

import type { Tables, Enums } from "./db/database.types";

// ============================================================================
// 1. COMMON TYPES
// ============================================================================

/**
 * Pagination metadata returned with list endpoints
 */
export interface PaginationMetaDTO {
  total: number;
  limit: number;
  offset: number;
}

/**
 * Generic paginated response wrapper
 */
export interface PaginatedResponseDTO<T> {
  data: T[];
  pagination: PaginationMetaDTO;
}

/**
 * Validation error details - maps field names to error messages
 */
export type ValidationErrorDetailsDTO = Record<string, string>;

/**
 * Standard error response structure
 */
export interface ErrorResponseDTO {
  error: string;
  message: string;
  details?: ValidationErrorDetailsDTO;
}

/**
 * Rate limit error response (extends standard error)
 */
export interface RateLimitErrorResponseDTO extends ErrorResponseDTO {
  retry_after: number;
}

// ============================================================================
// 2. PROFILE DTOs
// ============================================================================

/**
 * Profile response - directly maps to profiles table
 * Used by: GET /api/v1/profile, PATCH /api/v1/profile
 */
export type ProfileResponseDTO = Tables<"profiles">;

/**
 * Update profile request
 * Currently empty but reserved for future extensions (e.g., display name, preferences)
 */
export type UpdateProfileRequestDTO = Record<string, never>;

// ============================================================================
// 3. CALORIE GOALS DTOs
// ============================================================================

/**
 * Calorie goal response - directly maps to calorie_goals table
 * Used by: GET /api/v1/calorie-goals/:id, GET /api/v1/calorie-goals/current
 */
export type CalorieGoalResponseDTO = Tables<"calorie_goals">;

/**
 * Create calorie goal request
 * Only daily_goal is provided; effective_from is calculated as CURRENT_DATE + 1
 */
export interface CreateCalorieGoalRequestDTO {
  daily_goal: number;
}

/**
 * Update calorie goal request
 * Allows modification of daily_goal value
 */
export interface UpdateCalorieGoalRequestDTO {
  daily_goal: number;
}

/**
 * Paginated list of calorie goals
 * Used by: GET /api/v1/calorie-goals
 */
export type CalorieGoalsListResponseDTO = PaginatedResponseDTO<CalorieGoalResponseDTO>;

// ============================================================================
// 4. AI GENERATIONS DTOs
// ============================================================================

/**
 * AI generation response - directly maps to ai_generations table
 * Used by: POST /api/v1/ai-generations, GET /api/v1/ai-generations/:id
 */
export type AIGenerationResponseDTO = Tables<"ai_generations">;

/**
 * Create AI generation request
 * Only the prompt is provided; all other fields are generated by the system
 */
export interface CreateAIGenerationRequestDTO {
  prompt: string;
}

/**
 * Paginated list of AI generations
 * Used by: GET /api/v1/ai-generations
 */
export type AIGenerationsListResponseDTO = PaginatedResponseDTO<AIGenerationResponseDTO>;

// ============================================================================
// 5. MEALS DTOs
// ============================================================================

/**
 * Nested AI generation information included in meal responses
 * Contains a subset of fields from ai_generations table
 */
export interface MealAIGenerationInfoDTO {
  id: string;
  prompt: string;
  assumptions: string | null;
  model_used: string | null;
  generation_duration: number | null;
}

/**
 * Meal response with optional nested AI generation info
 * Used by: GET /api/v1/meals/:id, GET /api/v1/meals
 */
export interface MealResponseDTO extends Tables<"meals"> {
  ai_generation?: MealAIGenerationInfoDTO;
}

/**
 * Base fields common to all meal creation requests
 */
interface CreateMealBaseRequestDTO {
  description: string;
  calories: number;
  protein?: number | null;
  carbs?: number | null;
  fats?: number | null;
  category?: Enums<"meal_category"> | null;
  meal_timestamp: string;
}

/**
 * Create AI-generated meal request
 * Requires ai_generation_id to link to the AI generation
 */
export interface CreateAIMealRequestDTO extends CreateMealBaseRequestDTO {
  input_method: "ai";
  ai_generation_id: string;
}

/**
 * Create manual meal request
 * No ai_generation_id required
 */
export interface CreateManualMealRequestDTO extends CreateMealBaseRequestDTO {
  input_method: "manual";
}

/**
 * Union type for meal creation - either AI or manual
 */
export type CreateMealRequestDTO = CreateAIMealRequestDTO | CreateManualMealRequestDTO;

/**
 * Update meal request - all fields optional for partial updates
 * Note: When editing AI-generated meals, input_method should be changed to 'ai-edited'
 */
export interface UpdateMealRequestDTO {
  description?: string;
  calories?: number;
  protein?: number | null;
  carbs?: number | null;
  fats?: number | null;
  category?: Enums<"meal_category"> | null;
  meal_timestamp?: string;
  input_method?: Enums<"input_method_type">;
}

/**
 * Warning message for meal creation/update
 * Used when calculated calories from macros differ from provided calories
 */
export interface MealWarningDTO {
  field: string;
  message: string;
}

/**
 * Meal creation response with warnings
 * Used by: POST /api/v1/meals
 */
export interface CreateMealResponseDTO extends Tables<"meals"> {
  warnings: MealWarningDTO[];
}

/**
 * Meal update response with warnings
 * Used by: PATCH /api/v1/meals/:id
 */
export interface UpdateMealResponseDTO extends Tables<"meals"> {
  warnings: MealWarningDTO[];
}

/**
 * Paginated list of meals with optional AI generation info
 * Used by: GET /api/v1/meals
 */
export type MealsListResponseDTO = PaginatedResponseDTO<MealResponseDTO>;

// ============================================================================
// 6. DAILY PROGRESS DTOs
// ============================================================================

/**
 * Daily progress status enum
 * Calculated based on total_calories vs calorie_goal
 */
export type DailyProgressStatus = "under" | "on_track" | "over";

/**
 * Daily progress response
 * Based on daily_progress view with additional computed status field
 * All fields are required (non-nullable) in responses
 */
export interface DailyProgressResponseDTO {
  date: string;
  user_id: string;
  total_calories: number;
  total_protein: number;
  total_carbs: number;
  total_fats: number;
  calorie_goal: number;
  percentage: number;
  status: DailyProgressStatus;
}

/**
 * Paginated list of daily progress records
 * Used by: GET /api/v1/daily-progress
 */
export type DailyProgressListResponseDTO = PaginatedResponseDTO<DailyProgressResponseDTO>;

// ============================================================================
// EXPORT ALL ENUMS FROM DATABASE TYPES
// ============================================================================

/**
 * Re-export database enums for convenience
 */
export type AIGenerationStatus = Enums<"ai_generation_status">;
export type InputMethodType = Enums<"input_method_type">;
export type MealCategory = Enums<"meal_category">;
