-- migration: create_enums
-- description: creates enum types for meal categories, input methods, and ai generation status
-- tables affected: none (prerequisite for meals and ai_generations tables)
-- notes: these enums must be created before the respective tables

-- create enum for meal categories
-- used to categorize meals into standard meal times
-- values are in english for database consistency, frontend will handle translations
create type meal_category as enum (
  'breakfast',  -- śniadanie
  'lunch',      -- obiad
  'dinner',     -- kolacja
  'snack',      -- przekąska
  'other'       -- inne
);

comment on type meal_category is 'categorizes meals into standard meal times (breakfast, lunch, dinner, snack, other)';

-- create enum for input method tracking
-- used to track how meal data was entered and modified
-- critical for ai metrics from prd (trust metric, usefulness metric)
create type input_method_type as enum (
  'ai',         -- generated by ai and accepted without edits
  'manual',     -- manually entered by user
  'ai-edited'   -- generated by ai but modified by user
);

comment on type input_method_type is 'tracks the source and modification status of meal data for ai metrics';

-- create enum for ai generation status
-- used to track the lifecycle of ai generation requests
-- enables monitoring and debugging of ai service
create type ai_generation_status as enum (
  'pending',    -- generation in progress
  'completed',  -- generation successful
  'failed'      -- generation failed
);

comment on type ai_generation_status is 'tracks status of ai generation requests (pending, completed, failed)';
