-- migration: create_meals
-- description: creates the meals table for storing user meal entries
-- tables affected: meals (new)
-- notes: core table for mvp, stores both ai-generated and manually entered meals
--        tracks input_method for ai metrics calculation
--        macronutrients (protein, carbs, fats) are optional, only calories required

-- create meals table
-- stores meal entries with nutritional information
-- supports both ai-generated and manual entry methods
create table meals (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references profiles(id) on delete cascade,

  -- meal description (used for both ai input and manual entry)
  description varchar(500) not null,

  -- nutritional information
  -- only calories are required, macronutrients are optional
  calories integer not null check (calories > 0 and calories <= 10000),
  protein decimal(6,2) check (protein >= 0 and protein <= 1000),
  carbs decimal(6,2) check (carbs >= 0 and carbs <= 1000),
  fats decimal(6,2) check (fats >= 0 and fats <= 1000),

  -- optional categorization (breakfast, lunch, dinner, snack, other)
  category meal_category,

  -- tracking for ai metrics (critical for prd requirements)
  -- ai: generated by ai and accepted without edits
  -- manual: manually entered by user
  -- ai-edited: generated by ai but modified by user
  input_method input_method_type not null,

  -- ai-specific data
  -- assumptions displayed to user (e.g., "large bowl = 450ml")
  ai_assumptions text,

  -- ai generation duration in milliseconds (for performance monitoring)
  ai_generation_duration integer,

  -- when the meal was consumed (not when it was entered)
  -- application validates: no future timestamps allowed
  meal_timestamp timestamptz not null,

  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

comment on table meals is 'user meal entries with nutritional information';
comment on column meals.id is 'primary key';
comment on column meals.user_id is 'foreign key to profiles';
comment on column meals.description is 'meal description (ai input or manual entry)';
comment on column meals.calories is 'calories in kcal (required, 1-10000)';
comment on column meals.protein is 'protein in grams (optional, 0-1000)';
comment on column meals.carbs is 'carbohydrates in grams (optional, 0-1000)';
comment on column meals.fats is 'fats in grams (optional, 0-1000)';
comment on column meals.category is 'optional meal category (breakfast, lunch, dinner, snack, other)';
comment on column meals.input_method is 'how meal was entered: ai, manual, or ai-edited (required for metrics)';
comment on column meals.ai_assumptions is 'assumptions made by ai (e.g., portion sizes)';
comment on column meals.ai_generation_duration is 'time taken for ai to generate response in milliseconds';
comment on column meals.meal_timestamp is 'when the meal was consumed (no future dates allowed)';
comment on column meals.created_at is 'timestamp when meal entry was created';
comment on column meals.updated_at is 'timestamp when meal entry was last updated';

-- create indexes for efficient queries
-- compound index supports dashboard and day view queries
create index idx_meals_user_id on meals(user_id);
create index idx_meals_user_timestamp on meals(user_id, meal_timestamp desc);

comment on index idx_meals_user_timestamp is
  'optimizes dashboard queries (list of days) and day view queries (meals for a day)';

-- enable row level security
alter table meals enable row level security;

-- rls policy: allow users to view their own meals
create policy "users can view own meals"
  on meals
  for select
  to authenticated
  using (user_id = auth.uid());

comment on policy "users can view own meals" on meals is
  'allows authenticated users to view only their own meal entries';

-- rls policy: allow users to insert their own meals
create policy "users can insert own meals"
  on meals
  for insert
  to authenticated
  with check (user_id = auth.uid());

comment on policy "users can insert own meals" on meals is
  'allows authenticated users to create meal entries only for themselves';

-- rls policy: allow users to update their own meals
create policy "users can update own meals"
  on meals
  for update
  to authenticated
  using (user_id = auth.uid());

comment on policy "users can update own meals" on meals is
  'allows authenticated users to update only their own meal entries';

-- rls policy: allow users to delete their own meals
create policy "users can delete own meals"
  on meals
  for delete
  to authenticated
  using (user_id = auth.uid());

comment on policy "users can delete own meals" on meals is
  'allows authenticated users to delete only their own meal entries';
